### ISSUE TITLE
multiple bug in texteffect2

### ISSUE THREAD

**Issue by chezsick** [chexov/fmwconcepts-imagemagicktools#1]
hi, there some option in texteffect2 are congeal, `-p` is always to 200 and the contrast and brightness is impossible to change negate value.

maybe there other bug in the script

Thanks

**Comment by seovchinnikov** [comment]
Hey!
Was it fixed?

**Comment by chezsick** [comment]
Excuse me, i think ils exist sorry
Here :::::: http://www.fmwconcepts.com/imagemagick/texteffect2/index.php you can added ans fixed, please
